name: transformer-emojis
channels:
  - defaults
dependencies:
  - black=19.3b0
  - pip=19.3.1
  - scikit-learn=0.21.3
  - pip:
    - tensorboardx==1.9
    - torch==1.3.1
    - tqdm==4.40.0
    - transformers==2.2.1
    - tweepy==3.8.0

